version: '3.8'

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nw_pfo2
    ports:
      - "3307:3306"

  backend:
    container_name:: backend
    image: sebamamby/backend:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - nw_pfo2

  static:
    container_name:: static
    image: sebamamby/static:latest
    ports:
      - "8080:80"
    networks:
      - nw_pfo2

networks:
  nw_pfo2:
    name: nw_pfo2

volumes: 
  mysql_data: 