FROM nginx:latest

WORKDIR /usr/share/nginx/html

# Eliminar el contenido por defecto de Nginx
RUN rm -rf ./*

# Copiar tu contenido estático al directorio de Nginx
COPY . /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]